build:
  default:
    image: golang:1.5
    environment:
      - CGO_ENABLED=0
    commands:
      - make deps
      - make vet
      - make build
      - make test
    when:
      repo: drone-plugins/drone-anynines
  armhf:
    image: armhfbuild/golang:1.5
    environment:
      - CGO_ENABLED=0
    commands:
      - make deps
      - make vet
      - make build
      - make test
    when:
      repo: armhf-drone-plugins/drone-anynines

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-anynines
    tag: latest
    when:
      repo: drone-plugins/drone-anynines
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: armhfplugins/drone-anynines
    storage_driver: overlay
    tag: latest
    when:
      repo: armhf-drone-plugins/drone-anynines
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-anynines
    tag: develop
    when:
      branch: develop
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: armhfplugins/drone-anynines
    storage_driver: overlay
    tag: latest
    when:
      repo: armhf-drone-plugins/drone-anynines
      branch: develop

plugin:
  name: Anynines
  desc: Deploy or update a project on Anynines
  type: deploy
  image: plugins/drone-anynines
  labels:
    - anynines
    - paas
