# escape=`
FROM plugins/base:windows-ltsc2022-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Anynines" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

# TODO: install required tools

ADD release\drone-anynines.exe c:\drone-anynines.exe
ENTRYPOINT [ "c:\\drone-anynines.exe" ]
